### ISSUE TITLE
Flex box and shadows are not supported.

### ISSUE THREAD

**Issue by sudharsanmit** [rse/node-prince#12]
Pls refer to the input and the output files attached. A simple html with shadows does not render to pdf correctly.

Thanks.
[design_new.pdf](https://github.com/rse/node-prince/files/880289/design_new.pdf)
[design_new.zip](https://github.com/rse/node-prince/files/880291/design_new.zip) [Input html inside]

**Comment by rse** [comment]
Well, that's an issue with PrinceXML itself, not the Node integration this "node-prince" module provides. You have to report those issues to the PrinceXML tool vendor, please
