### ISSUE TITLE
Update Prince Version

### ISSUE THREAD

**Issue by dhollenbeck** [rse/node-prince#24]
After an Windows update my version of prince which is installed via `node_prince` no longer. The issue is documented: https://www.princexml.com/forum/topic/3871/princexml-not-working-after-windows-update

The issue is was resolved my updating prince_npm.js to the latest versions.

I would be happy to issue a pull request if you indicate you will consider merging it.

**Comment by rse** [comment]
We are now downloading PrinceXML 12.3 and as a workaround you always can locally install PrinceXML and place it into your %PATH%.
