### ISSUE TITLE
--debug option doesn't work

### ISSUE THREAD

**Issue by niksajanjic** [rse/node-prince#25]
Looking at this link https://www.princexml.com/doc/command-line/ seems like this wrapper doesn't support many options without forcing it. Debug option should be provided without having to force it which is the first issue. But, even if it's forced, with the current code it will not work.

To make it work there should be some changes made to the `child_process.execFile` function inside `_execute` function. Adding something as a callback function of `child_process.execFile` in these lines would fix it:

```js
if (self.config.option.debug) {
  const msgs = stderr.toString().split('\n')
  msgs.forEach(msg => {
    msg.match(/prince:/) && console.log(msg)
  })
}
```

**Comment by rse** [comment]
The "debug" option is now recognized and no longer has to be forced. But I do not get the point of extracting the debug messages from stderr, as stderr is passed to the caller anyway. He can extract the data himself, as with all the other data in stdout/stderr. Why should be specially process debug messages on stderr but not other messages?

**Comment by niksajanjic** [comment]
I have no strong opinion on how this should've been fixed, this was just sort of example of what would fix it, not saying that this was a proper fix. Just wanted to report that some options won't work without forcing and that `--debug` option wasn't enabled. After that, it was just an attempt to show what I added to the module to temporarily fix it for myself locally (which was just for dev purposes, I didn't need it in production). I'm going to assume it's fixed as you said and close the issue.
