### ISSUE TITLE
Check for installed prince version not working with v10r3-1

### ISSUE THREAD

**Issue by shanebell** [rse/node-prince#3]
With version `10r3-1` of prince installed from http://www.princexml.com/download/ the regex check on line 63 of prince-npm.js does not work.

    var m = stdout.match(/^Prince\s+(\d+\.\d+)/);

The version returned by `$ prince --version` is `Prince 10 rev 3` which does not match the above. The code then goes on to download prince and install it even though it's already installed.

**Comment by rse** [comment]
Now fixed in version 1.1.4. Thanks for the hint.

**Comment by shanebell** [comment]
Awesome. Thanks for the speedy fix :)
