### ISSUE TITLE
ERROR: PrinceXML not available for platform "arm-macosx11.5"

### ISSUE THREAD

**Issue by shawnthompson** [rse/node-prince#36]
Can't be run on Apple Silicon device. 

Might be something you could put as a notice on the README.md.

Can't wait for PrinceXML supports ARM architecture.

**Comment by wezm** [comment]
The Intel version of Prince will run on ARM Macs for now. To use it with this package, you need to install it manually, instead of using the automatic installation feature of `node-prince`. https://www.princexml.com/download/

**Comment by shawnthompson** [comment]
Thank you very much
