### ISSUE TITLE
Supporting execution of --raster-output without  --output

### ISSUE THREAD

**Issue by frederik** [rse/node-prince#38]
Thanks for maintaining this library 🤗 

I would like to achieve an export of images à la

```
prince input.html --raster-format=jpeg --raster-pages=first --raster-dpi=90 --raster-output=page.jpg
```

But would need --output to be optional for that, since [raster-output](https://www.princexml.com/doc/command-line/#raster-output-options) is used.

A workaround is to supply both options and just disregard the file produced by output, but it'd be nice to drop the option. I'd be happy to submit a pull request, where output is not forced when raster-output is set as an option.

```
Prince({
            'raster-format': 'jpeg',
            'raster-pages': 'first',
            'raster-dpi': 90,
            'raster-background': 'white',
            'raster-output': 'page.jpg'
        })
            [..]
            .output('unused')
[..]
```

Kindly
Frederik

**Comment by rse** [comment]
Good idea. Thanks for the hint. Now implemented in 1.9.2.
