### ISSUE TITLE
Bump to r7?

### ISSUE THREAD

**Issue by runemadsen** [rse/node-prince#6]
Should this package install the newest version of Prince?

**Comment by rse** [comment]
No, it has to know the version-specific download URLs of PrinceXML, so it installs the latest version I configured at the time of the release of this package. The new version 1.2.0 is now based on PrinceXML 10r7. But once 10r8 comes out we have to upgrade it again, of course.

**Comment by runemadsen** [comment]
Great, that's what I meant. Thanks for all the hard work on this. It makes it ridicously easy to use Prince in API's
